// AUTO-GENERATED by scripts/build-data-bundle.ts — DO NOT EDIT BY HAND.
// Run `pnpm build-data-bundle` after adding/removing dialogues, concepts,
// or decks. The data is statically imported so it lives inside the SSR
// bundle — required by Cloudflare Workers since public/*.json is served
// via the ASSETS binding, not accessible from `node:fs` at runtime.

/* eslint-disable */

import BP_asking_directions_a1 from "../../public/dialogues/blueprints/asking_directions_a1.json" with { type: "json" };
import BP_cap_theorem_explain_b2 from "../../public/dialogues/blueprints/cap_theorem_explain_b2.json" with { type: "json" };
import BP_coffee_shop_order_a1 from "../../public/dialogues/blueprints/coffee_shop_order_a1.json" with { type: "json" };
import BP_doctor_visit_a2 from "../../public/dialogues/blueprints/doctor_visit_a2.json" with { type: "json" };
import BP_friends_catching_up_b1 from "../../public/dialogues/blueprints/friends_catching_up_b1.json" with { type: "json" };
import BP_greetings_a1 from "../../public/dialogues/blueprints/greetings_a1.json" with { type: "json" };
import BP_hotel_check_in_a2 from "../../public/dialogues/blueprints/hotel_check_in_a2.json" with { type: "json" };
import BP_morning_commute_a2 from "../../public/dialogues/blueprints/morning_commute_a2.json" with { type: "json" };
import BP_restaurant_dinner_b1 from "../../public/dialogues/blueprints/restaurant_dinner_b1.json" with { type: "json" };
import BP_salary_negotiation_b2 from "../../public/dialogues/blueprints/salary_negotiation_b2.json" with { type: "json" };

import TR_asking_directions_a1__de from "../../public/dialogues/translations/asking_directions_a1/de.json" with { type: "json" };
import TR_asking_directions_a1__en from "../../public/dialogues/translations/asking_directions_a1/en.json" with { type: "json" };
import TR_asking_directions_a1__es from "../../public/dialogues/translations/asking_directions_a1/es.json" with { type: "json" };
import TR_asking_directions_a1__it from "../../public/dialogues/translations/asking_directions_a1/it.json" with { type: "json" };
import TR_asking_directions_a1__ja from "../../public/dialogues/translations/asking_directions_a1/ja.json" with { type: "json" };
import TR_asking_directions_a1__ko from "../../public/dialogues/translations/asking_directions_a1/ko.json" with { type: "json" };
import TR_asking_directions_a1__zh_tw from "../../public/dialogues/translations/asking_directions_a1/zh-tw.json" with { type: "json" };
import TR_cap_theorem_explain_b2__de from "../../public/dialogues/translations/cap_theorem_explain_b2/de.json" with { type: "json" };
import TR_cap_theorem_explain_b2__en from "../../public/dialogues/translations/cap_theorem_explain_b2/en.json" with { type: "json" };
import TR_cap_theorem_explain_b2__es from "../../public/dialogues/translations/cap_theorem_explain_b2/es.json" with { type: "json" };
import TR_cap_theorem_explain_b2__it from "../../public/dialogues/translations/cap_theorem_explain_b2/it.json" with { type: "json" };
import TR_cap_theorem_explain_b2__ja from "../../public/dialogues/translations/cap_theorem_explain_b2/ja.json" with { type: "json" };
import TR_cap_theorem_explain_b2__ko from "../../public/dialogues/translations/cap_theorem_explain_b2/ko.json" with { type: "json" };
import TR_cap_theorem_explain_b2__zh_tw from "../../public/dialogues/translations/cap_theorem_explain_b2/zh-tw.json" with { type: "json" };
import TR_coffee_shop_order_a1__de from "../../public/dialogues/translations/coffee_shop_order_a1/de.json" with { type: "json" };
import TR_coffee_shop_order_a1__en from "../../public/dialogues/translations/coffee_shop_order_a1/en.json" with { type: "json" };
import TR_coffee_shop_order_a1__es from "../../public/dialogues/translations/coffee_shop_order_a1/es.json" with { type: "json" };
import TR_coffee_shop_order_a1__it from "../../public/dialogues/translations/coffee_shop_order_a1/it.json" with { type: "json" };
import TR_coffee_shop_order_a1__ja from "../../public/dialogues/translations/coffee_shop_order_a1/ja.json" with { type: "json" };
import TR_coffee_shop_order_a1__ko from "../../public/dialogues/translations/coffee_shop_order_a1/ko.json" with { type: "json" };
import TR_coffee_shop_order_a1__zh_tw from "../../public/dialogues/translations/coffee_shop_order_a1/zh-tw.json" with { type: "json" };
import TR_doctor_visit_a2__de from "../../public/dialogues/translations/doctor_visit_a2/de.json" with { type: "json" };
import TR_doctor_visit_a2__en from "../../public/dialogues/translations/doctor_visit_a2/en.json" with { type: "json" };
import TR_doctor_visit_a2__es from "../../public/dialogues/translations/doctor_visit_a2/es.json" with { type: "json" };
import TR_doctor_visit_a2__it from "../../public/dialogues/translations/doctor_visit_a2/it.json" with { type: "json" };
import TR_doctor_visit_a2__ja from "../../public/dialogues/translations/doctor_visit_a2/ja.json" with { type: "json" };
import TR_doctor_visit_a2__ko from "../../public/dialogues/translations/doctor_visit_a2/ko.json" with { type: "json" };
import TR_doctor_visit_a2__zh_tw from "../../public/dialogues/translations/doctor_visit_a2/zh-tw.json" with { type: "json" };
import TR_friends_catching_up_b1__de from "../../public/dialogues/translations/friends_catching_up_b1/de.json" with { type: "json" };
import TR_friends_catching_up_b1__en from "../../public/dialogues/translations/friends_catching_up_b1/en.json" with { type: "json" };
import TR_friends_catching_up_b1__es from "../../public/dialogues/translations/friends_catching_up_b1/es.json" with { type: "json" };
import TR_friends_catching_up_b1__it from "../../public/dialogues/translations/friends_catching_up_b1/it.json" with { type: "json" };
import TR_friends_catching_up_b1__ja from "../../public/dialogues/translations/friends_catching_up_b1/ja.json" with { type: "json" };
import TR_friends_catching_up_b1__ko from "../../public/dialogues/translations/friends_catching_up_b1/ko.json" with { type: "json" };
import TR_friends_catching_up_b1__zh_tw from "../../public/dialogues/translations/friends_catching_up_b1/zh-tw.json" with { type: "json" };
import TR_greetings_a1__de from "../../public/dialogues/translations/greetings_a1/de.json" with { type: "json" };
import TR_greetings_a1__en from "../../public/dialogues/translations/greetings_a1/en.json" with { type: "json" };
import TR_greetings_a1__es from "../../public/dialogues/translations/greetings_a1/es.json" with { type: "json" };
import TR_greetings_a1__it from "../../public/dialogues/translations/greetings_a1/it.json" with { type: "json" };
import TR_greetings_a1__ja from "../../public/dialogues/translations/greetings_a1/ja.json" with { type: "json" };
import TR_greetings_a1__ko from "../../public/dialogues/translations/greetings_a1/ko.json" with { type: "json" };
import TR_greetings_a1__zh_tw from "../../public/dialogues/translations/greetings_a1/zh-tw.json" with { type: "json" };
import TR_hotel_check_in_a2__de from "../../public/dialogues/translations/hotel_check_in_a2/de.json" with { type: "json" };
import TR_hotel_check_in_a2__en from "../../public/dialogues/translations/hotel_check_in_a2/en.json" with { type: "json" };
import TR_hotel_check_in_a2__es from "../../public/dialogues/translations/hotel_check_in_a2/es.json" with { type: "json" };
import TR_hotel_check_in_a2__it from "../../public/dialogues/translations/hotel_check_in_a2/it.json" with { type: "json" };
import TR_hotel_check_in_a2__ja from "../../public/dialogues/translations/hotel_check_in_a2/ja.json" with { type: "json" };
import TR_hotel_check_in_a2__ko from "../../public/dialogues/translations/hotel_check_in_a2/ko.json" with { type: "json" };
import TR_hotel_check_in_a2__zh_tw from "../../public/dialogues/translations/hotel_check_in_a2/zh-tw.json" with { type: "json" };
import TR_morning_commute_a2__de from "../../public/dialogues/translations/morning_commute_a2/de.json" with { type: "json" };
import TR_morning_commute_a2__en from "../../public/dialogues/translations/morning_commute_a2/en.json" with { type: "json" };
import TR_morning_commute_a2__es from "../../public/dialogues/translations/morning_commute_a2/es.json" with { type: "json" };
import TR_morning_commute_a2__it from "../../public/dialogues/translations/morning_commute_a2/it.json" with { type: "json" };
import TR_morning_commute_a2__ja from "../../public/dialogues/translations/morning_commute_a2/ja.json" with { type: "json" };
import TR_morning_commute_a2__ko from "../../public/dialogues/translations/morning_commute_a2/ko.json" with { type: "json" };
import TR_morning_commute_a2__zh_tw from "../../public/dialogues/translations/morning_commute_a2/zh-tw.json" with { type: "json" };
import TR_restaurant_dinner_b1__de from "../../public/dialogues/translations/restaurant_dinner_b1/de.json" with { type: "json" };
import TR_restaurant_dinner_b1__en from "../../public/dialogues/translations/restaurant_dinner_b1/en.json" with { type: "json" };
import TR_restaurant_dinner_b1__es from "../../public/dialogues/translations/restaurant_dinner_b1/es.json" with { type: "json" };
import TR_restaurant_dinner_b1__it from "../../public/dialogues/translations/restaurant_dinner_b1/it.json" with { type: "json" };
import TR_restaurant_dinner_b1__ja from "../../public/dialogues/translations/restaurant_dinner_b1/ja.json" with { type: "json" };
import TR_restaurant_dinner_b1__ko from "../../public/dialogues/translations/restaurant_dinner_b1/ko.json" with { type: "json" };
import TR_restaurant_dinner_b1__zh_tw from "../../public/dialogues/translations/restaurant_dinner_b1/zh-tw.json" with { type: "json" };
import TR_salary_negotiation_b2__de from "../../public/dialogues/translations/salary_negotiation_b2/de.json" with { type: "json" };
import TR_salary_negotiation_b2__en from "../../public/dialogues/translations/salary_negotiation_b2/en.json" with { type: "json" };
import TR_salary_negotiation_b2__es from "../../public/dialogues/translations/salary_negotiation_b2/es.json" with { type: "json" };
import TR_salary_negotiation_b2__it from "../../public/dialogues/translations/salary_negotiation_b2/it.json" with { type: "json" };
import TR_salary_negotiation_b2__ja from "../../public/dialogues/translations/salary_negotiation_b2/ja.json" with { type: "json" };
import TR_salary_negotiation_b2__ko from "../../public/dialogues/translations/salary_negotiation_b2/ko.json" with { type: "json" };
import TR_salary_negotiation_b2__zh_tw from "../../public/dialogues/translations/salary_negotiation_b2/zh-tw.json" with { type: "json" };

import CONCEPTS_BASE from "../../public/concepts/concepts.json" with { type: "json" };
import CT_de from "../../public/concepts/translations/de.json" with { type: "json" };
import CT_en from "../../public/concepts/translations/en.json" with { type: "json" };
import CT_es from "../../public/concepts/translations/es.json" with { type: "json" };
import CT_it from "../../public/concepts/translations/it.json" with { type: "json" };
import CT_ja from "../../public/concepts/translations/ja.json" with { type: "json" };
import CT_ko from "../../public/concepts/translations/ko.json" with { type: "json" };
import CT_zh_tw from "../../public/concepts/translations/zh-tw.json" with { type: "json" };

import DK_body_parts_a1 from "../../public/decks/body_parts_a1.json" with { type: "json" };
import DK_common_objects_a1 from "../../public/decks/common_objects_a1.json" with { type: "json" };
import DK_emotions_a1 from "../../public/decks/emotions_a1.json" with { type: "json" };
import DK_family_a1 from "../../public/decks/family_a1.json" with { type: "json" };
import DK_food_a1 from "../../public/decks/food_a1.json" with { type: "json" };
import DK_ja_hiragana_basic_a1 from "../../public/decks/ja_hiragana_basic_a1.json" with { type: "json" };
import DK_ja_hiragana_dakuten_a1 from "../../public/decks/ja_hiragana_dakuten_a1.json" with { type: "json" };
import DK_ja_hiragana_yoon_a1 from "../../public/decks/ja_hiragana_yoon_a1.json" with { type: "json" };
import DK_ja_katakana_basic_a1 from "../../public/decks/ja_katakana_basic_a1.json" with { type: "json" };
import DK_ja_katakana_dakuten_a1 from "../../public/decks/ja_katakana_dakuten_a1.json" with { type: "json" };
import DK_ja_katakana_yoon_a1 from "../../public/decks/ja_katakana_yoon_a1.json" with { type: "json" };
import DK_kitchen_a1 from "../../public/decks/kitchen_a1.json" with { type: "json" };
import DK_ko_hangul_aspirated_a1 from "../../public/decks/ko_hangul_aspirated_a1.json" with { type: "json" };
import DK_ko_hangul_basic_a1 from "../../public/decks/ko_hangul_basic_a1.json" with { type: "json" };
import DK_ko_hangul_palatalized_a1 from "../../public/decks/ko_hangul_palatalized_a1.json" with { type: "json" };
import DK_numbers_a1 from "../../public/decks/numbers_a1.json" with { type: "json" };
import DK_time_a1 from "../../public/decks/time_a1.json" with { type: "json" };
import DK_transportation_a1 from "../../public/decks/transportation_a1.json" with { type: "json" };
import DK_travel_a1 from "../../public/decks/travel_a1.json" with { type: "json" };
import DK_weather_a1 from "../../public/decks/weather_a1.json" with { type: "json" };

export const BUNDLED_BLUEPRINTS: Record<string, unknown> = {
  "asking_directions_a1": BP_asking_directions_a1,
  "cap_theorem_explain_b2": BP_cap_theorem_explain_b2,
  "coffee_shop_order_a1": BP_coffee_shop_order_a1,
  "doctor_visit_a2": BP_doctor_visit_a2,
  "friends_catching_up_b1": BP_friends_catching_up_b1,
  "greetings_a1": BP_greetings_a1,
  "hotel_check_in_a2": BP_hotel_check_in_a2,
  "morning_commute_a2": BP_morning_commute_a2,
  "restaurant_dinner_b1": BP_restaurant_dinner_b1,
  "salary_negotiation_b2": BP_salary_negotiation_b2,
};

export const BUNDLED_TRANSLATIONS: Record<string, Record<string, unknown>> = {
  "asking_directions_a1": {
    "de": TR_asking_directions_a1__de,
    "en": TR_asking_directions_a1__en,
    "es": TR_asking_directions_a1__es,
    "it": TR_asking_directions_a1__it,
    "ja": TR_asking_directions_a1__ja,
    "ko": TR_asking_directions_a1__ko,
    "zh-tw": TR_asking_directions_a1__zh_tw,
  },
  "cap_theorem_explain_b2": {
    "de": TR_cap_theorem_explain_b2__de,
    "en": TR_cap_theorem_explain_b2__en,
    "es": TR_cap_theorem_explain_b2__es,
    "it": TR_cap_theorem_explain_b2__it,
    "ja": TR_cap_theorem_explain_b2__ja,
    "ko": TR_cap_theorem_explain_b2__ko,
    "zh-tw": TR_cap_theorem_explain_b2__zh_tw,
  },
  "coffee_shop_order_a1": {
    "de": TR_coffee_shop_order_a1__de,
    "en": TR_coffee_shop_order_a1__en,
    "es": TR_coffee_shop_order_a1__es,
    "it": TR_coffee_shop_order_a1__it,
    "ja": TR_coffee_shop_order_a1__ja,
    "ko": TR_coffee_shop_order_a1__ko,
    "zh-tw": TR_coffee_shop_order_a1__zh_tw,
  },
  "doctor_visit_a2": {
    "de": TR_doctor_visit_a2__de,
    "en": TR_doctor_visit_a2__en,
    "es": TR_doctor_visit_a2__es,
    "it": TR_doctor_visit_a2__it,
    "ja": TR_doctor_visit_a2__ja,
    "ko": TR_doctor_visit_a2__ko,
    "zh-tw": TR_doctor_visit_a2__zh_tw,
  },
  "friends_catching_up_b1": {
    "de": TR_friends_catching_up_b1__de,
    "en": TR_friends_catching_up_b1__en,
    "es": TR_friends_catching_up_b1__es,
    "it": TR_friends_catching_up_b1__it,
    "ja": TR_friends_catching_up_b1__ja,
    "ko": TR_friends_catching_up_b1__ko,
    "zh-tw": TR_friends_catching_up_b1__zh_tw,
  },
  "greetings_a1": {
    "de": TR_greetings_a1__de,
    "en": TR_greetings_a1__en,
    "es": TR_greetings_a1__es,
    "it": TR_greetings_a1__it,
    "ja": TR_greetings_a1__ja,
    "ko": TR_greetings_a1__ko,
    "zh-tw": TR_greetings_a1__zh_tw,
  },
  "hotel_check_in_a2": {
    "de": TR_hotel_check_in_a2__de,
    "en": TR_hotel_check_in_a2__en,
    "es": TR_hotel_check_in_a2__es,
    "it": TR_hotel_check_in_a2__it,
    "ja": TR_hotel_check_in_a2__ja,
    "ko": TR_hotel_check_in_a2__ko,
    "zh-tw": TR_hotel_check_in_a2__zh_tw,
  },
  "morning_commute_a2": {
    "de": TR_morning_commute_a2__de,
    "en": TR_morning_commute_a2__en,
    "es": TR_morning_commute_a2__es,
    "it": TR_morning_commute_a2__it,
    "ja": TR_morning_commute_a2__ja,
    "ko": TR_morning_commute_a2__ko,
    "zh-tw": TR_morning_commute_a2__zh_tw,
  },
  "restaurant_dinner_b1": {
    "de": TR_restaurant_dinner_b1__de,
    "en": TR_restaurant_dinner_b1__en,
    "es": TR_restaurant_dinner_b1__es,
    "it": TR_restaurant_dinner_b1__it,
    "ja": TR_restaurant_dinner_b1__ja,
    "ko": TR_restaurant_dinner_b1__ko,
    "zh-tw": TR_restaurant_dinner_b1__zh_tw,
  },
  "salary_negotiation_b2": {
    "de": TR_salary_negotiation_b2__de,
    "en": TR_salary_negotiation_b2__en,
    "es": TR_salary_negotiation_b2__es,
    "it": TR_salary_negotiation_b2__it,
    "ja": TR_salary_negotiation_b2__ja,
    "ko": TR_salary_negotiation_b2__ko,
    "zh-tw": TR_salary_negotiation_b2__zh_tw,
  },
};

export const BUNDLED_CONCEPTS_BASE: unknown = CONCEPTS_BASE;
export const BUNDLED_CONCEPT_TRANSLATIONS: Record<string, unknown> = {
  "de": CT_de,
  "en": CT_en,
  "es": CT_es,
  "it": CT_it,
  "ja": CT_ja,
  "ko": CT_ko,
  "zh-tw": CT_zh_tw,
};

export const BUNDLED_DECKS: Record<string, unknown> = {
  "body_parts_a1": DK_body_parts_a1,
  "common_objects_a1": DK_common_objects_a1,
  "emotions_a1": DK_emotions_a1,
  "family_a1": DK_family_a1,
  "food_a1": DK_food_a1,
  "ja_hiragana_basic_a1": DK_ja_hiragana_basic_a1,
  "ja_hiragana_dakuten_a1": DK_ja_hiragana_dakuten_a1,
  "ja_hiragana_yoon_a1": DK_ja_hiragana_yoon_a1,
  "ja_katakana_basic_a1": DK_ja_katakana_basic_a1,
  "ja_katakana_dakuten_a1": DK_ja_katakana_dakuten_a1,
  "ja_katakana_yoon_a1": DK_ja_katakana_yoon_a1,
  "kitchen_a1": DK_kitchen_a1,
  "ko_hangul_aspirated_a1": DK_ko_hangul_aspirated_a1,
  "ko_hangul_basic_a1": DK_ko_hangul_basic_a1,
  "ko_hangul_palatalized_a1": DK_ko_hangul_palatalized_a1,
  "numbers_a1": DK_numbers_a1,
  "time_a1": DK_time_a1,
  "transportation_a1": DK_transportation_a1,
  "travel_a1": DK_travel_a1,
  "weather_a1": DK_weather_a1,
};

export const BUNDLED_BLUEPRINT_IDS: readonly string[] = ["asking_directions_a1","cap_theorem_explain_b2","coffee_shop_order_a1","doctor_visit_a2","friends_catching_up_b1","greetings_a1","hotel_check_in_a2","morning_commute_a2","restaurant_dinner_b1","salary_negotiation_b2"];
export const BUNDLED_DECK_IDS: readonly string[] = ["body_parts_a1","common_objects_a1","emotions_a1","family_a1","food_a1","ja_hiragana_basic_a1","ja_hiragana_dakuten_a1","ja_hiragana_yoon_a1","ja_katakana_basic_a1","ja_katakana_dakuten_a1","ja_katakana_yoon_a1","kitchen_a1","ko_hangul_aspirated_a1","ko_hangul_basic_a1","ko_hangul_palatalized_a1","numbers_a1","time_a1","transportation_a1","travel_a1","weather_a1"];
