#!/usr/bin/env tsx
/**
 * audit-vocab — survey the current vocab data and produce a markdown
 * report:
 *
 *   - per-CEFR concept count vs the targets in OPEN_ISSUES.md G6+
 *   - per-language translation coverage
 *   - missing visuals (concepts lacking `visual.kind`)
 *   - concepts missing POS / frequency tags after G3
 *   - decks with stale or out-of-range concept ids
 *
 * Output: `docs/AUDIT_VOCAB.md`. Stdout summarises the high-impact gaps.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import {
  ConceptsFileSchema,
  TranslationsFileSchema,
} from "../lib/data/vocab/schema";

const ROOT = path.resolve(process.cwd(), "public", "concepts");
const CONCEPTS_FILE = path.join(ROOT, "concepts.json");
const TRANSLATIONS_DIR = path.join(ROOT, "translations");
const DECKS_FILE = path.join(ROOT, "decks.json");
const REPORT = path.resolve(process.cwd(), "docs", "AUDIT_VOCAB.md");

interface DeckEntry {
  id: string;
  conceptIds: string[];
}

const CEFR_TARGETS: Record<string, number> = {
  A1: 1000,
  A2: 2000,
  B1: 5000,
  B2: 8000,
  C1: 10000,
};

async function readJson<T>(file: string): Promise<T | null> {
  try {
    const raw = await fs.readFile(file, "utf-8");
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

async function listTranslationFiles(): Promise<string[]> {
  try {
    return await fs.readdir(TRANSLATIONS_DIR);
  } catch {
    return [];
  }
}

async function main(): Promise<void> {
  const parsed = ConceptsFileSchema.parse(
    JSON.parse(await fs.readFile(CONCEPTS_FILE, "utf-8")),
  );
  const concepts = parsed.concepts;

  const cefrCounts = new Map<string, number>();
  let missingVisual = 0;
  let missingPos = 0;
  let missingFrequency = 0;
  for (const c of concepts) {
    cefrCounts.set(c.cefr, (cefrCounts.get(c.cefr) ?? 0) + 1);
    if (!c.visual) missingVisual += 1;
    if (!c.pos) missingPos += 1;
    if (!c.frequency) missingFrequency += 1;
  }

  // Translations per language.
  const langFiles = await listTranslationFiles();
  const langCoverage = new Map<string, number>();
  const conceptIds = new Set(concepts.map((c) => c.id));
  const orphanTranslations = new Map<string, string[]>();
  for (const f of langFiles) {
    if (!f.endsWith(".json")) continue;
    const langPath = path.join(TRANSLATIONS_DIR, f);
    const raw = await readJson<unknown>(langPath);
    if (!raw) continue;
    const parsedT = TranslationsFileSchema.safeParse(raw);
    if (!parsedT.success) continue;
    const lang = parsedT.data.language;
    let covered = 0;
    const orphans: string[] = [];
    for (const t of parsedT.data.translations) {
      if (conceptIds.has(t.conceptId)) covered += 1;
      else orphans.push(t.conceptId);
    }
    langCoverage.set(lang, covered);
    if (orphans.length > 0) orphanTranslations.set(lang, orphans);
  }

  // Decks.
  const decks =
    (await readJson<{ decks: DeckEntry[] }>(DECKS_FILE))?.decks ?? [];
  const staleDecks: { id: string; missing: string[] }[] = [];
  for (const d of decks) {
    const missing = d.conceptIds.filter((cid) => !conceptIds.has(cid));
    if (missing.length > 0) staleDecks.push({ id: d.id, missing });
  }

  // Build the report.
  const lines: string[] = [
    "# Vocab Audit",
    "",
    `Generated by \`scripts/audit-vocab.ts\` on ${new Date().toISOString()}.`,
    "",
    `Total concepts: **${concepts.length}**`,
    "",
    "## CEFR coverage vs targets",
    "",
    "| Level | Current | Target (G6+) | Δ |",
    "|---|---|---|---|",
  ];
  let runningTotal = 0;
  for (const level of ["A1", "A2", "B1", "B2", "C1"]) {
    const cur = cefrCounts.get(level) ?? 0;
    runningTotal += cur;
    const target = CEFR_TARGETS[level];
    const delta = runningTotal - target;
    lines.push(
      `| ${level} | ${cur} (Σ ${runningTotal}) | ${target} | ${delta} |`,
    );
  }

  lines.push(
    "",
    "## Schema completeness",
    "",
    `- Concepts without \`visual\`: **${missingVisual}** (run \`pnpm assign-visuals\`)`,
    `- Concepts without \`pos\`: **${missingPos}**`,
    `- Concepts without \`frequency\`: **${missingFrequency}**`,
    "",
    "## Translation coverage (by language)",
    "",
    "| Language | Translations matching a concept |",
    "|---|---|",
  );
  for (const [lang, n] of Array.from(langCoverage.entries()).sort()) {
    lines.push(`| ${lang} | ${n} / ${concepts.length} |`);
  }

  if (orphanTranslations.size > 0) {
    lines.push(
      "",
      "## Orphan translations (point to non-existent concepts)",
      "",
    );
    for (const [lang, ids] of orphanTranslations) {
      lines.push(`- **${lang}**: ${ids.slice(0, 10).join(", ")}${ids.length > 10 ? `, … (+${ids.length - 10} more)` : ""}`);
    }
  }

  if (staleDecks.length > 0) {
    lines.push("", "## Stale decks", "");
    for (const d of staleDecks) {
      lines.push(`- **${d.id}** references missing concept ids: ${d.missing.join(", ")}`);
    }
  }

  lines.push("");
  await fs.writeFile(REPORT, lines.join("\n"), "utf-8");

  process.stdout.write(
    `Vocab audit complete. ${concepts.length} concepts, ${langCoverage.size} languages. Report at ${path.relative(process.cwd(), REPORT)}.\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`audit-vocab failed: ${String(err)}\n`);
  process.exit(1);
});
