#!/usr/bin/env tsx
/**
 * build-data-bundle — generate lib/data/data-bundle.ts.
 *
 * Cloudflare Workers can't read public/*.json via `fs.readFile` at runtime
 * (those files live in the static-asset bucket, not in the worker bundle).
 * We sidestep that by importing every data JSON statically — Next.js inlines
 * the contents into the SSR bundle so the loaders can resolve them with
 * zero filesystem calls.
 *
 * Run on every commit that adds / removes a dialogue / concept / deck:
 *
 *   pnpm build-data-bundle
 *
 * Output:
 *   lib/data/data-bundle.ts  (committed)
 */

import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(process.cwd());
const PUB = path.join(ROOT, "public");

function rel(p: string): string {
  return path.relative(path.join(ROOT, "lib", "data"), p).replace(/\\/g, "/");
}

async function listJsons(dir: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(dir);
    return entries.filter((f) => f.endsWith(".json")).sort();
  } catch {
    return [];
  }
}

async function listDirs(dir: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

function keyName(prefix: string, slug: string): string {
  return `${prefix}_${slug.replace(/[^a-zA-Z0-9]/g, "_")}`;
}

async function main(): Promise<void> {
  const blueprintFiles = await listJsons(
    path.join(PUB, "dialogues", "blueprints"),
  );
  const blueprintIds = blueprintFiles.map((f) => f.replace(/\.json$/, ""));

  const translationDirs = await listDirs(
    path.join(PUB, "dialogues", "translations"),
  );

  const deckFiles = await listJsons(path.join(PUB, "decks"));
  const deckIds = deckFiles.map((f) => f.replace(/\.json$/, ""));

  const conceptLangs = (
    await listJsons(path.join(PUB, "concepts", "translations"))
  ).map((f) => f.replace(/\.json$/, ""));

  const lines: string[] = [];
  lines.push(
    "// AUTO-GENERATED by scripts/build-data-bundle.ts — DO NOT EDIT BY HAND.",
    "// Run `pnpm build-data-bundle` after adding/removing dialogues, concepts,",
    "// or decks. The data is statically imported so it lives inside the SSR",
    "// bundle — required by Cloudflare Workers since public/*.json is served",
    "// via the ASSETS binding, not accessible from `node:fs` at runtime.",
    "",
    "/* eslint-disable */",
    "",
  );

  // Blueprints.
  for (const id of blueprintIds) {
    const file = path.join(PUB, "dialogues", "blueprints", `${id}.json`);
    lines.push(
      `import ${keyName("BP", id)} from "${rel(file)}" with { type: "json" };`,
    );
  }
  lines.push("");

  // Dialogue translations.
  const translationKeys: { id: string; lang: string; key: string }[] = [];
  for (const id of translationDirs) {
    const langs = (
      await listJsons(path.join(PUB, "dialogues", "translations", id))
    ).map((f) => f.replace(/\.json$/, ""));
    for (const lang of langs) {
      const file = path.join(
        PUB,
        "dialogues",
        "translations",
        id,
        `${lang}.json`,
      );
      const key = keyName("TR", `${id}__${lang}`);
      translationKeys.push({ id, lang, key });
      lines.push(`import ${key} from "${rel(file)}" with { type: "json" };`);
    }
  }
  lines.push("");

  // Concepts.
  const conceptsFile = path.join(PUB, "concepts", "concepts.json");
  lines.push(
    `import CONCEPTS_BASE from "${rel(conceptsFile)}" with { type: "json" };`,
  );
  for (const lang of conceptLangs) {
    const file = path.join(PUB, "concepts", "translations", `${lang}.json`);
    lines.push(
      `import ${keyName("CT", lang)} from "${rel(file)}" with { type: "json" };`,
    );
  }
  lines.push("");

  // Decks.
  for (const id of deckIds) {
    const file = path.join(PUB, "decks", `${id}.json`);
    lines.push(
      `import ${keyName("DK", id)} from "${rel(file)}" with { type: "json" };`,
    );
  }
  lines.push("");

  // Public exports.
  lines.push("export const BUNDLED_BLUEPRINTS: Record<string, unknown> = {");
  for (const id of blueprintIds) {
    lines.push(`  ${JSON.stringify(id)}: ${keyName("BP", id)},`);
  }
  lines.push("};");
  lines.push("");

  lines.push(
    "export const BUNDLED_TRANSLATIONS: Record<string, Record<string, unknown>> = {",
  );
  const grouped = new Map<string, { lang: string; key: string }[]>();
  for (const t of translationKeys) {
    const list = grouped.get(t.id) ?? [];
    list.push({ lang: t.lang, key: t.key });
    grouped.set(t.id, list);
  }
  for (const [id, entries] of grouped) {
    lines.push(`  ${JSON.stringify(id)}: {`);
    for (const e of entries) {
      lines.push(`    ${JSON.stringify(e.lang)}: ${e.key},`);
    }
    lines.push(`  },`);
  }
  lines.push("};");
  lines.push("");

  lines.push("export const BUNDLED_CONCEPTS_BASE: unknown = CONCEPTS_BASE;");
  lines.push(
    "export const BUNDLED_CONCEPT_TRANSLATIONS: Record<string, unknown> = {",
  );
  for (const lang of conceptLangs) {
    lines.push(`  ${JSON.stringify(lang)}: ${keyName("CT", lang)},`);
  }
  lines.push("};");
  lines.push("");

  lines.push("export const BUNDLED_DECKS: Record<string, unknown> = {");
  for (const id of deckIds) {
    lines.push(`  ${JSON.stringify(id)}: ${keyName("DK", id)},`);
  }
  lines.push("};");
  lines.push("");

  lines.push(
    "export const BUNDLED_BLUEPRINT_IDS: readonly string[] = " +
      JSON.stringify(blueprintIds) +
      ";",
  );
  lines.push(
    "export const BUNDLED_DECK_IDS: readonly string[] = " +
      JSON.stringify(deckIds) +
      ";",
  );
  lines.push("");

  const out = path.join(ROOT, "lib", "data", "data-bundle.ts");
  await fs.writeFile(out, lines.join("\n"), "utf-8");

  console.log(
    `wrote ${out} — ${blueprintIds.length} blueprints, ${translationKeys.length} translations, ${conceptLangs.length} concept langs, ${deckIds.length} decks`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
